steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA', '.']
    id: 'Build Docker image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA']
    id: 'Push Docker image to GCR'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/flask-app
      - flask-app=gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=' #zone here
      - 'CLOUDSDK_CONTAINER_CLUSTER=' #cluster name here
    id: 'Deploy to GKE'

  - name: 'gcr.io/cloud-builders/helm'
    args:
      - upgrade
      - --install
      - flask-app
      - ./helm-chart
      - --set
      - image.repository=gcr.io/$PROJECT_ID/flask-app
      - --set
      - image.tag=$COMMIT_SHA
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=' #zone here
      - 'CLOUDSDK_CONTAINER_CLUSTER=' #cluster name here
    id: 'Deploy with Helm'

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'
