name: Deploy to GKE with Cloud Build

on:
  push:
    branches:
      - main

jobs:
  trigger-cloud-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Trigger Cloud Build
        run: gcloud builds submit --config cloudbuild.yaml .
